refact
NikitaDembitsky/tictactoe pull request #2
Opened 2021-07-14 13:41 UTC by NikitaDembitsky

2021-07-15 07:56 UTC, eugene-ryabov requested changes

2021-07-15 07:56 UTC, eugene-ryabov commented on src/components/Game/Game.tsx
> +const alculateWinner = (squares: SquareValue[]): SquareValue => {
вынеси это в отдельный файл (например `utils.ts`)

2021-07-15 07:56 UTC, eugene-ryabov commented on src/types.ts
> +export type SquareValue = Symbol.X | Symbol.O | null;
Так будет лучше. Каждое значение енума не надо перечеслять
`export type SquareValue = Symbol | null;`

2021-07-15 07:56 UTC, eugene-ryabov commented on src/components/Square/Square.tsx
> +const Square: React.FC<SquareProps> = (props) => {
Сделай деструктуризацию пропсов. С ней будет выглядеть лучше код

2021-07-15 07:56 UTC, eugene-ryabov commented on src/components/Game/Game.tsx
> +  const lines = [
Можно вынести в константу

2021-07-15 07:56 UTC, eugene-ryabov commented on src/components/Game/Game.tsx
> +      status = "Next player: " + (xIsNext ? "X" : "O");
так как X и O у тебя уже есть в енуме, то можно сделать что-то такое `(xIsNext ? Symbol.X : Symbol.O);`

2021-07-15 07:56 UTC, eugene-ryabov commented on src/components/Game/Game.tsx
> +  const winner = alculateWinner(current.squares);
букву в слове пропустил

2021-07-15 07:56 UTC, eugene-ryabov commented on src/components/Game/Game.tsx
> +  const [history, setHistory] = useState<{ squares: SquareValue[] }[]>([
Добавь свой хук для history

2021-07-15 10:09 UTC, NikitaDembitsky reviewed
fix

2021-07-16 06:01 UTC, eugene-ryabov requested changes

2021-07-16 06:01 UTC, eugene-ryabov commented on src/hooks/useHistory.ts
> +function useHistory(): any {
Сделай стрелочную функцию

2021-07-16 06:01 UTC, eugene-ryabov commented on src/hooks/useHistory.ts
> +function useHistory(): any {
Добавь возвращаемый тип вместо any

2021-07-16 06:01 UTC, eugene-ryabov commented on src/components/Game/Game.tsx
> +  const checkWinner = (xIsNext: any, winner: any) => {
тоже вынеси в сервисы

2021-07-16 06:01 UTC, eugene-ryabov commented on src/constants.ts
> +export const lines = [
Имена констант пишутся в upper case

2021-07-16 06:01 UTC, eugene-ryabov commented on src/constants.ts
> +export const lines = [
лучше назвать `winningGrid`. Лучше передает, что это за массив

2021-07-16 07:08 UTC, eugene-ryabov approved these changes

2021-07-16 07:11 UTC, merged